project:
  type: website
  output-dir: docs

website:
  title: "Elly Kirwa"
  description: "Graduate Research Assistant - PhD Student"
  site-url: https://ellykp.github.io
  favicon: misc/info/favicon.png
  repo-url: https://github.com/EllyKp/ellykp.github.io
  repo-actions: [edit, issue]
  page-navigation: true

  page-footer:
    left: >-
      &#169; 2026 Elly Kirwa &#8729; Made with <a href="https://quarto.org" target="_blank">Quarto</a>
    center: |
      <a class="link-dark me-2" href="https://www.linkedin.com/in/elly-kirwa-04a351123/" title="LinkedIn" target="_blank" rel="noopener"><i class="fab fa-linkedin"></i></a>
      <a class="link-dark me-2" href="https://github.com/EllyKp" title="GitHub" target="_blank" rel="noopener"><i class="fab fa-github"></i></a>
    right:
      - text: "Contact"
        aria-label: "Contact Form"
        href: contact.qmd

  navbar:
    background: "#A9CCE3"
    search: true
    right:
      - text: ""
        href: "#"
        id: theme-toggle
      - text: About
        icon: person-circle
        href: about_me.qmd
      - text: CV
        icon: file-earmark-text-fill
        href: cv.qmd
      - text: "Research"
        icon: lightbulb-fill
        href: rpkg/research.qmd
      - text: "Projects & Notes"
        icon: puzzle-fill
        menu:
          - text: "✨ All Projects"
            href: projects.qmd
      - text: "Teaching"
        icon: mortarboard-fill
        href: teaching/teaching.qmd
      - text: "Blogs"
        icon: pen-fill
        href: blog/index.qmd

format:
  html:
    theme:
      light: styles.scss
      dark: styles-dark.scss
    include-after-body:
      - theme-toggle.html
      - theme-toggle.js
    math: mathjax
    html-math-method: mathjax
    toc: true
    citeproc: false
    toc-depth: 3
    smooth-scroll: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

bibliography: references.bib
filters:
  - custom-bib-links.lua
